version: "3.8"
services:
  backend-test:
    build:
      context: ./src/api
    command: sh -c "PYTHONPATH=/app pytest"
    volumes:
      - .:/app

  backend:
    build:
      context: ./src/api
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/app

  frontend:
    build: ./src/frontend
    ports:
      - "80:3000"
    depends_on:
      - backend